name = "chatapp/testchat"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
enable_go_build_cache = false
skip_runtime_image = true
go_version = "1.19.3"

[builders."exec:go"]
enabled = true
[runners."local:exec"]
enabled = true
[runners."local:docker"]
enabled = true

[[testcases]]
name= "chatapp/testchat"
instances = { min = 1, max = 150, default = 1 }
