/*
* @Author: Joakim
* @Year: 2022
* @Description:
* File is used to create a loader of the
* smart contract aginst a specific ethereum node to test it
* when first creating the smart contract.
* Used the instructions from the Go developer book at
* https://goethereumbook.org/en/.
 */

package main

import (
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"

	state "github.com/luxfeerre/thesis-chatapp/chatapp/state"
)

func contract_load() {
	// Change this to your specific ethereum full node
	client, err := ethclient.Dial("http://192.168.1.221:8552")
	if err != nil {
		log.Fatal(err)
	}
	// Change to the specific Ethereum smart contract address generated by deployer
	address := common.HexToAddress("0x99ddD1DF9C9719294e8cD34B1FFCC6B03CfFeBB0")
	instance, err := state.NewState(address, client)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("contract is loaded")
	_ = instance
}
